print("input NAME:")
Name=input()
print("Name: "+Name)
print("input Last name:")
LastName=input()
print("Last name: "+LastName)
print("input age:")
age=input()
print("Age: "+age)
#print("\nHello "+LastName+" "+Name+' and you are '+age)
#print('Age: ',16,' You rell age?')
print(f"\nHello {LastName} {Name} and you are {age}")